### PR TITLE
(emacs) show log of process input / output

### PR DESCRIPTION
**Pull request by mgsloan**
@gracjan Please review.  I'm rather new to elisp.

This makes the `*hie*` buffer accumulate a log of `<- input` and `-> output`, like:

```
-> {"cmd":"base:commandDetail","params":{"command":{"text":"type"},"plugin":{"text":"ghcmod"}}}
<- {"contexts":["point"],"return_type":"TypeInfo","plugin_name":"ghcmod","name":"type","additional_params":[],"ui_description":"Get the type of the expression under (LINE,COL)","file_extensions":[".hs",".lhs"]}
-> {"cmd":"ghcmod:type","params":{"file":{"file":"\/home\/mgsloan\/fpco\/stack\/src\/Stack\/BuildPlan.hs"},"start_pos":{"line":272,"col":79},"end_pos":{"line":272,"col":79}}}
<- {"type_info":[{"start":{"line":272,"col":79},"end":{"line":272,"col":84},"type":"PackageIdentifier"},{"start":{"line":272,"col":57},"end":{"line":272,"col":84},"type":"PackageName"},{"start":{"line":272,"col":56},"end":{"line":272,"col":85},"type":"PackageName"},{"start":{"line":272,"col":45},"end":{"line":272,"col":85},"type":"Map PackageName (Stack.Types.Version.Version, Map FlagName Bool) -> Maybe (Stack.Types.Version.Version, Map FlagName Bool)"},{"start":{"line":272,"col":45},"end":{"line":272,"col":92},"type":"Maybe (Stack.Types.Version.Version, Map FlagName Bool)"},{"start":{"line":272,"col":23},"end":{"line":272,"col":92},"type":"Map FlagName Bool"},{"start":{"line":270,"col":22},"end":{"line":273,"col":22},"type":"(PackageIdentifier, PackageCache, Map FlagName Bool)"},{"start":{"line":270,"col":21},"end":{"line":273,"col":23},"type":"[(PackageIdentifier, PackageCache, Map FlagName Bool)]"},{"start":{"line":269,"col":17},"end":{"line":273,"col":24},"type":"(IndexName, [(PackageIdentifier, PackageCache, Map FlagName Bool)])"},{"start":{"line":268,"col":15},"end":{"line":273,"col":24},"type":"(PackageIdentifier, ResolvedPackage) -> (IndexName, [(PackageIdentifier, PackageCache, Map FlagName Bool)])"},{"start":{"line":267,"col":43},"end":{"line":273,"col":24},"type":"[(IndexName, [(PackageIdentifier, PackageCache, Map FlagName Bool)])]"},{"start":{"line":267,"col":19},"end":{"line":273,"col":24},"type":"Map IndexName [(PackageIdentifier, PackageCache, Map FlagName Bool)]"},{"start":{"line":267,"col":9},"end":{"line":273,"col":24},"type":"Map IndexName [(PackageIdentifier, PackageCache, Map FlagName Bool)]"},{"start":{"line":254,"col":47},"end":{"line":299,"col":54},"type":"m (Map PackageName MiniPackageInfo, Set PackageIdentifier)"},{"start":{"line":254,"col":1},"end":{"line":303,"col":28},"type":"Bool -> CompilerVersion -> Map PackageName (Stack.Types.Version.Version, Map FlagName Bool) -> m (Map PackageName MiniPackageInfo, Set PackageIdentifier)"}]}
```

In the long run this might be information overload, and shouldn't be a default.

In particular, `hie-log` is based on [`stack-mode-log`](https://github.com/commercialhaskell/stack-ide/blob/master/stack-mode/stack-mode.el#L665).  stack-ide.el may be an interesting thing to take a look in general.

### CODE REVIEW

**Comment by mgsloan** [comment]
@cocreature Thanks for the comments on https://github.com/haskell/haskell-ide-engine/commit/d49d0 , I've force pushed a modified commit.

**Comment by mgsloan** [comment]
I've pushed another commit which changes the code quite a bit, and fixes the test results (which are very helpful!)

**Comment by mgsloan** [comment]
Oof, there are some tricky interactions between `hie-log` and chunkwise consuming input from the process....

I think this needs a different approach, so closing.

**Comment by mgsloan** [comment]
Pushed a completely different approach: have a separate *hie-log* buffer.

**Comment by mgsloan** [comment]
Huh, I guess I can't reopen a PR for a force pushed branch.  I've opened a new PR

**Comment by gracjan** [comment]
@mgsloan, sorry for being late to this party, you did a good thing. `*hie*` is just an implementation detail, should never be show to user. I like your `*hie-log*` approach!

**Pull request closed without merging**
