### PR TITLE
Fix build for Windows 7

### PR DESCRIPTION
**Pull request by jneira**
* Actually the project cant be built in windows 7 due a bug in the package `unix-time` (via `hoogle` -> `wai-logger` -> `fast-logger`)
* The issue was resolved in the package: see https://github.com/kazu-yamamoto/unix-time/issues/51
* The first version of the package with the fix was `0.4.7`

This pr update the resolver for `stack-yaml` and `stack-8.6.5.yaml` to get one with the patched version and add `unix-time-0.4.7` as exta dependency for the rest of stack config files.

### CODE REVIEW

**Comment by alanz** [comment]
In order to minimise rebuilding for people using hie, we try to only bump resolvers once a month.

Can we maybe just add the extra dep for GHC 8.6.5 and the nightly stack, until they get bumped at the end of the month?

**Comment by jneira** [comment]
@alanz of course! cache is very valuable with so many deps

**Comment by alanz** [comment]
Thanks, LGTM. We can merge this when CI passes

**Comment by alanz** [comment]
And it just struck me we should add

```
unix-time >= 0.4.7
```
to the cabal file somewhere.

**Comment by jneira** [comment]
@alanz maybe it would be not neccesary (other than doing a `cabal update`) cause:
* wai-logger has not upper bound on fast-logger
* fast-logger has not upper bound on unix-time

it doesnt follow pvp but you have the last patched version without hackage revisions in exchange.
I havent tested it though.

**Comment by alanz** [comment]
Fair enough, but I think I will be happier to actively constrain a lower bound on it, as per #1306

**Pull request merged**
