### PR TITLE
Use  haskell-src-exts 1.22

### LINKED ISSUE #1649: Hlint issue with QuantifiedConstraints
Originally reported [on the hlint repo](https://github.com/ndmitchell/hlint/issues/866).

Using a quantified constraint results in an 'illegal class assertion error' coming from the hlint parser. But the same version of hlint (2.2.10), run as a standalone executable, parses the file with no issues.

### PR DESCRIPTION
**Pull request by jneira**
It will need to be rebased onto #1678 
Fixes #1649

### CODE REVIEW

**Comment by jneira** [comment]
One of the needed changes had been to bump hlint version to `5.0.17.15`

**Comment by fendor** [comment]
Please rebase changes!

**Comment by jneira** [comment]
@fendor done! but i've got locally the same error with askUnliftIO

**Comment by jneira** [comment]
I am constraining unliftio-core to fix the build, @alanz could we include this in the release if the build get fixed?

**Pull request merged**
