### PR TITLE
Add integration test for hie-hare-rename

### PR DESCRIPTION
**Pull request by cocreature**

### CODE REVIEW

**Comment by cocreature** [comment]
If anybody has an idea why this fails on travis I would be very happy. I don’t really know where to look.

**Comment by bergey** [comment]
I get the same error locally if I reduce the 2-second delay.  (The one after `hie-hare-rename`).  Maybe this pause needs to be longer on travis?

**Comment by cocreature** [comment]
Thanks @bergey that was it

**Comment by alanz** [comment]
Nice to see this

**Pull request merged**
