### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by rasendubi**
PR for https://github.com/haskell/haskell-ide-engine/issues/159.

### CODE REVIEW

**Comment by cocreature** [comment]
Thanks! Could you please put the partial type signatures pack in and enable in those files `{-# OPTIONS_GHC -fno-warn-partial-type-signatures #-}`, the types don’t help here.

Also I’ll leave it to @alanz to decide whether we should enable `-Werror`. We should definitely remove it when we release but until then I like the idea of enabling it.

**Comment by glittershark** [comment]
could have a cabal flag that's off-by-default to have it only enable on travis

**Comment by cocreature** [comment]
A cabal flag sounds like a good idea.

**Comment by DanielG** [comment]
+1 for having a default off flag for -Werror that's on on travis. It's that's very annoying during development.

**Comment by mgsloan** [comment]
Agreed, and a cabal flag is not necessary.  This can be done by invoking `stack build` with `--pedantic`.

**Comment by rasendubi** [comment]
@mgsloan `--pedantic` passes `-Werror` to all underlying libraries which eventually fails to build because of warnings in ghc-mod.

**Comment by cocreature** [comment]
Maybe we just need to annoy @mgsloan enough so that he fixes that for us :)

**Comment by alanz** [comment]
+1

**Comment by mgsloan** [comment]
Ah, it isn't that it gets passed to underlying libraries in general.  Looks like there's a bug with packages that are marked `extra-dep: True`, where `ghc-options` are erroneously applied to them.

I didn't know about this bug, and I don't think the stack issue tracker did either.  I've opened https://github.com/commercialhaskell/stack/issues/1631

**Comment by rasendubi** [comment]
@mgsloan see https://github.com/commercialhaskell/stack/issues/1292

**Comment by mgsloan** [comment]
Gotcha.  I knew the issue sounded familiar!  Didn't find it since I was searching for ghc-options rather than pedantic

**Comment by cocreature** [comment]
So what do we do here? It seems like the options are either adding a flag or removing the `-Werror`. I don’t really care what we decide to do, but I don’t want this PR to sit around waiting just because of that reason.

**Comment by glittershark** [comment]
I'm ++ for the flag

**Comment by alanz** [comment]
Perhaps remove -Werror, and then build with --pedantic once the bug is
fixed there

**Comment by cocreature** [comment]
Since we are now back to having two options and two people each favoring one of those, let’s just go with a flag for now so we can merge this ( @rasendubi please add that). Once `--pedantic` is actually usable again, we can kill it.

**Comment by alanz** [comment]
ok

**Comment by cocreature** [comment]
Closing in favor of #171

**Pull request closed without merging**
