### PR TITLE
Trying out haskell-lsp 0.14

### PR DESCRIPTION
**Pull request by alanz**
Tests failing, suspect a JSON encoding problem.

ping @cocreature, see the circle logs

Locally I get the first two of many failing tests, all with a spurious `<0>`

```
      test/functional/FunctionalCodeActionsSpec.hs:557:9: 
      1) FunctionalCodeActions, code actions, import suggestions, formats with brittany, Execute HsImport with formatter brittany, works with 3.8 code action kinds
           expected: "Import module Control.Monad (when)"
            but got: "Import module Control.Monad (<0>when)"
    
      To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with brittany/Execute HsImport with formatter brittany/works with 3.8 code action kinds/"
    
      test/functional/FunctionalCodeActionsSpec.hs:598:16: 
      2) FunctionalCodeActions, code actions, import suggestions, formats with brittany, Execute HsImport with formatter brittany, import-list formats
           Actual list is not a permutation of expected list!
             expected list contains:   ["import qualified Data.Maybe", "import           Control.Monad                  ( when )", "main :: IO ()", "main = when True $ putStrLn \"hello\""]
             actual list contains:     ["import qualified Data.Maybe", "import Control.Monad ((<0>when))", "main :: IO ()", "main = when True $ putStrLn \"hello\""]
             the missing elements are: ["import           Control.Monad                  ( when )"]
             the extra elements are:   ["import Control.Monad ((<0>when))"]
    
      To rerun use: --match "/FunctionalCodeActions/code actions/import suggestions/formats with brittany/Execute HsImport with formatter brittany/import-list formats/"
```

### CODE REVIEW

**Comment by fendor** [comment]
Did these errors happen before #1284 had been merged?

**Comment by alanz** [comment]
@fendor good point, I had forgotten about that.  We will have to see what circle says about the merge result. I assume it was fine, as it showed green on CI before I merged, and you had updated it recently.

**Comment by cocreature** [comment]
Hm, it looks unrelated to the changes I made but I could very well be wrong.

**Comment by alanz** [comment]
It looks like circle was happy with @fendor 's merge: https://circleci.com/workflow-run/fc727e9b-c6a9-4ed6-9f27-9f6332e248e8
I am building it locally too, to check, then will investigate the rest.

There is also an updated lsp-test, perhaps @bubba knows something about that.

**Comment by alanz** [comment]
Ok, seems there is something whacky on my local machine.

**Comment by bubba** [comment]
The functional tests for HIE passed for me on my own branch with LSP 0.14, but could be an OS specific thing

**Comment by alanz** [comment]
I am on linux too. But been messing with cabal builds, and ghc 8.8., etc. Could have a whacky config by now.

So I reckon just merge and see what happens. Circle is happy.

**Comment by alanz** [comment]
I did a bisect on this, and the problem comes from https://github.com/haskell/haskell-ide-engine/commit/3350686dc36c9ed012a817b6806ec1a34c4b2d05

```
$ git bisect log
git bisect start
# good: [83c28a907eda2a68aeeb254f8baa9f3add08aacf] Merge pull request #1287 from alanz/hlint-2.1.24
git bisect good 83c28a907eda2a68aeeb254f8baa9f3add08aacf
# bad: [d679eb595a6a1583a8b63a3fdd5964f84a8d00f6] Merge pull request #1288 from alanz/haskell-lsp-0.14
git bisect bad d679eb595a6a1583a8b63a3fdd5964f84a8d00f6
# bad: [988dcff2eb18edcee0bbed5a10e597f9ca9d1ad9] Add space to code action title
git bisect bad 988dcff2eb18edcee0bbed5a10e597f9ca9d1ad9
# bad: [3835a09db92c3a3c4f0761e50cd22e70f191c603] Fix tests, add documentation and add newtypes
git bisect bad 3835a09db92c3a3c4f0761e50cd22e70f191c603
# bad: [07822b472e0495a1819008362e53ad07e670fdc6] Add documentation for hsimport plugin
git bisect bad 07822b472e0495a1819008362e53ad07e670fdc6
# bad: [3350686dc36c9ed012a817b6806ec1a34c4b2d05] Clone HsImport API for more fine grained control
git bisect bad 3350686dc36c9ed012a817b6806ec1a34c4b2d05
# first bad commit: [3350686dc36c9ed012a817b6806ec1a34c4b2d05] Clone HsImport API for more fine grained control
```
I think that what is happening is that I have a full hoogle db locally, we don't have it on the CI box.

And we need to add something like https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/Hoogle.hs#L137 into it somewhere:

```haskell
        unHTML = T.replace "<0>" "" . innerText . parseTags
```

cc @fendor

**Comment by alanz** [comment]
And after deleting and re-creating my `~/.hoogle` directory as per the circleci config, the tests pass for me.

I tried creating additional hoogle generate dbs, but it still passes. I think there is a landmine waiting out there.

**Comment by fendor** [comment]
I have a good idea where this might be coming from. Hoogle `searchPackage'` defines almost exactly this function. In HsImport `importListActions` also obtains the function name by splitting "::". That may be wrong.

**Comment by fendor** [comment]
I think, the fix would be to adapt `searchPackage'` to use `unHtml` that will be merged via #1290

**Pull request merged**
