### PR TITLE
Fix multi source directories

### LINKED ISSUE #1576: HIE does not handle multiple source directories correctly
Error message:
```
2020-01-19 11:54:16.3609472 [ThreadId 103] - Fail on cradle initialisation: (ExitFailure 2)["Could not obtain flags for: \"src\\schema\\AnswerChoice.hs\".","","This module was not part of any component we are aware of.","","Component: ChLibName ChMainLibName with source directory: [\"src\",\"src/schema\",\"src/api\",\"src/Questions\",\"src/Users\"]","Component: ChExeName \"healthbot-api-exe\" with source directory: [\"app\"]","Component: ChExeName \"migrations\" with source directory: [\"migrations\"]","","","To expose a module, refer to:","https://docs.haskellstack.org/en/stable/GUIDE/","If you are using `package.yaml` then you don't have to manually expose modules.","Maybe you didn't set the source directories for your project correctly."]
2020-01-19 11:54:16.361947 [ThreadId 38] - ghcDispatcher:Got error for a request: IdeError {ideCode = OtherError, ideMessage = "Fail on initialisation for \"D:\\dev\\healthbot\\healthbot-api\\src\\schema\\AnswerChoice.hs\". Could not obtain flags for: \"src\\schema\\AnswerChoice.hs\".", ideInfo = Null} with mid: Nothing
```

Generated .cabal file.

```
-- This file has been generated from package.yaml by hpack version 0.31.1.
--
-- see: https://github.com/sol/hpack
--
-- hash: 8313da4611145f153645f4cdd683b1e59fa8a667a9a62f5484494f7a39934dfd

name:           healthbot-api
cabal-version:  >= 1.8
version:        0.1.0.0
description:    Please see the README on GitHub at <https://github.com/tuomohopia/healthbot-api#readme>
homepage:       https://github.com/tuomohopia/healthbot-api#readme
bug-reports:    https://github.com/tuomohopia/healthbot-api/issues
author:         Tuomo Hopia
maintainer:     tuomo.hopia@gmail.com
copyright:      2019 Tuomo Hopia
build-type:     Simple
extra-source-files:
    README.md
    ChangeLog.md

source-repository head
  type: git
  location: https://github.com/tuomohopia/healthbot-api

library
  default-language: Haskell2010
  exposed-modules:
      Lib
      , Config
      , Geolocation
      , AnswerChoice
      -- , QuestionBattery
      , Helpers
      , Gender
      , Api
      , ApiDocs
      -- , RootEndpoint
      , Auth
      , Schema
      , Database.Database
      , Database.Setup
      -- Users:
      , Users.Types
      , UsersEndpoint
      , Database.Query.Users
      -- Questions:
      , Questions.Types
      , QuestionsEndpoint
      , Database.Query.Questions
      -- Answers:
      , Answers.Types
      , Answers.AnswerMapping
      , AnswersEndpoint
      , Database.Query.Answers
      -- Next Questions
      , Nexts.QuestionBattery
  other-modules:
      Paths_healthbot_api
  hs-source-dirs:
      src
      , src/schema
      , src/api
      , src/Questions
      , src/Users
  build-depends:
      base >=4.7 && <5
      , text
      , time
      , aeson
      , mtl
      , bytestring
      , containers >=0.6.0.1
      , persistent-database-url
      , envy
      , transformers
      , monad-logger
      , servant
      , servant-server
      , servant-docs
      , wai
      , warp
      , email-validate
      , servant-auth
      , servant-auth-server
      , servant-auth-docs
      , servant-swagger
      , servant-auth-swagger
      , swagger2
      , jose
      , cookie
      , persistent-postgresql
      , squeal-postgresql
      , postgresql-binary
      , generics-sop
      , resource-pool
      , lens
      , aeson-pretty

executable healthbot-api-exe
  main-is: Main.hs
  other-modules:
      Paths_healthbot_api
  exposed-modules:
      Main
  hs-source-dirs:
      app
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      base >=4.7 && <5
    , healthbot-api
    , mtl
    , text
    , aeson
    , persistent
    , persistent-postgresql
    , persistent-template
    , monad-logger
    , time
    , transformers
    , containers >=0.6.0.1
    , envy
    , bytestring
    , wai
    , warp
    , persistent-database-url
    , servant
    , servant-server
    , servant-auth
    , servant-auth-server
  default-language: Haskell2010

executable migrations
  main-is: Main.hs
  other-modules:
      Paths_healthbot_api
  hs-source-dirs:
      migrations
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      base >=4.7 && <5
    , healthbot-api
    , mtl
    , text
    , persistent
    , persistent-postgresql
    , monad-logger
    , transformers
    , containers >=0.6.0.1
    , envy
    , bytestring
    , persistent-database-url
  default-language: Haskell2010

test-suite unit-tests
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
      Paths_healthbot_api, ConfigSpec, SeedData, SeedHelpers
  hs-source-dirs:
      test
      , test/unit
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      base >=4.7 && <5
    , healthbot-api
    , mtl
    , text
    , aeson
    , persistent
    , persistent-postgresql
    , persistent-template
    , monad-logger
    , time
    , transformers
    , containers >=0.6.0.1
    , envy
    , hspec
    , hspec-wai
    , bytestring
    , hspec-discover
    , wai
    , warp
    , servant-client
    , http-client
    , http-types
  default-language: Haskell2010

test-suite integration-tests
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
      Paths_healthbot_api, SeedHelpers, SeedHelpers, TestHelpers, SeedData, UsersEndpointSpec, QuestionsEndpointSpec, AnswersEndpointSpec
  hs-source-dirs:
      test
      , test/integration
      , app
  ghc-options: -threaded -rtsopts -with-rtsopts=-N
  build-depends:
      base >=4.7 && <5
    , healthbot-api
    , mtl
    , text
    , aeson
    , persistent
    , persistent-postgresql
    , persistent-template
    , persistent-database-url
    , monad-logger
    , time
    , transformers
    , containers >=0.6.0.1
    , envy
    , hspec
    , hspec-wai
    , hspec-wai-json
    , bytestring
    , hspec-discover
    , hspec-expectations-lifted
    , wai
    , warp
    , servant
    , servant-server
    , servant-client
    , http-client
    , http-types
    , servant-auth
    , servant-auth-server
    , servant-auth-client
    , jose
  default-language: Haskell2010
```

_Originally posted by @tuomohopia in https://github.com/haskell/haskell-ide-engine/issues/1564#issuecomment-575992033_

### PR DESCRIPTION
**Pull request by fendor**
Closes #1576

### CODE REVIEW

**Comment by fendor** [comment]
@tuomohopia Would you mind testing if this fixes your issues?

**Comment by jneira** [comment]
Some azure jobs are failing cause cabal-helper are trying to install Cabal-3.0.1.0, weird
```
haskell-ide-engine>   test/unit/CabalHelperSpec.hs:63:5: 
haskell-ide-engine>   1) CabalHelper, cabal-helper spec, cradle discovery and loading, existing projects, implicit exe
haskell-ide-engine>        uncaught exception: Panic
haskell-ide-engine>        panic! cabal-helper: Installing Cabal version 3.0.1.0 failed.
```

**Comment by tuomohopia** [comment]
@fendor 
Tests don't work yet, opening a test file in the editor would give the same error:
```
2020-01-20 00:09:39.7838711 [ThreadId 625] - Fail on cradle initialisation: (ExitFailure 2)["Could not obtain flags for: \"test\\integration\\AnswersEndpointSpec.hs\".","","This module was not part of any component we are aware of.","","Component: ChLibName ChMainLibName with source directory: [\"src\",\"src/schema\",\"src/api\",\"src/Questions\",\"src/Users\"]","Component: ChExeName \"healthbot-api-exe\" with source directory: [\"app\"]","Component: ChExeName \"migrations\" with source directory: [\"migrations\"]","","","To expose a module, refer to:","https://docs.haskellstack.org/en/stable/GUIDE/","If you are using `package.yaml` then you don't have to manually expose modules.","Maybe you didn't set the source directories for your project correctly."]
2020-01-20 00:09:39.7838711 [ThreadId 38] - ghcDispatcher:Got error for a request: IdeError {ideCode = OtherError, ideMessage = "Fail on initialisation for \"D:\\dev\\healthbot\\healthbot-api\\test\\integration\\AnswersEndpointSpec.hs\". Could not obtain flags for: \"test\\integration\\AnswersEndpointSpec.hs\".", ideInfo = Null} with mid: Nothing
```

However, as far as I can tell everything else works normally again!

**Comment by fendor** [comment]
@tuomohopia Yes, this does not aim to fix the tests but rather the observed behaviour with you main library. Fixing the problem with the test components is more elaborate and discussed at: https://github.com/DanielG/cabal-helper/pull/92

**Comment by fendor** [comment]
@jneira Any ideas what is going wrong or any fixes? 
We could make components loads dependent on the current build tool to execute?

**Comment by jneira** [comment]
> @jneira Any ideas what is going wrong or any fixes?
> We could make components loads dependent on the current build tool to execute?

Sorry i missed the mention, let's see how finish this run but i am very surprised to see a build of a version of a library not released

**Comment by fendor** [comment]
@jneira No problem! I disabled loading of components by cabal-helper to get this PR merged asap, so now we return to the status quo of the test-suite.
Situation should be improved by #1585

**Pull request merged**
