### PR TITLE
Quickfix action to prefix unused terms with '_'

### LINKED ISSUE #843: Add quickfix for unused variable warning
Generate an edit that prefixes an underscore char to the unused var.

### PR DESCRIPTION
**Pull request by meck**
This resolves #843

### CODE REVIEW

**Comment by lorenzo** [comment]
Can you please add a test for this?

**Comment by meck** [comment]
Of course!

**Comment by bubba** [comment]
@alanz @lorenzo should we turn on Haskell CI's CircleCI for PRs? I think it may currently only be running on our own individual accounts

**Comment by lorenzo** [comment]
I thought it was already on!

**Comment by meck** [comment]
Might be set to run PRs only after they are accepted?

**Comment by lorenzo** [comment]
I thought it was on already

**Comment by meck** [comment]
The circle ci issue was on my part. I had tinkered with it on my fork. And apparently if you watch a fork it dosen't build for PRs to upstream.

**Pull request merged**
