### PR TITLE
Reduce duplication in Haddock.hs

### PR DESCRIPTION
**Pull request by jhrcek**

### CODE REVIEW

**Comment by alanz** [comment]
LGTM

**Comment by jhrcek** [comment]
@alanz thanks for the review. Just wanted to check with you : what's the process for reviewing / merging of PRs (now that I'm a contributor and have merge rights)? Should I wait for other reviews? Can I merge the PR after I get an approval from other contributors or should I wait for others to merge it?

**Comment by alanz** [comment]
@jhrcek We do not really have a clear policy. 

Basically if at least one other person has said they are ok we can merge. I just held of a bit because the doc stuff had been done by @wz1000  / @bubba so I wanted to give them a chance to comment if they chose to.

**Comment by bubba** [comment]
A bit late to the party, but it's great to see this type of gardening. I'll make a tag for these types of PRs!

**Comment by jhrcek** [comment]
@bubba I'm glad you find it useful. It's my way of getting acquainted with the codebase in my free time. I'll create more PRs like these as I have time.

**Pull request merged**
