### PR TITLE
Add another feature example

### PR DESCRIPTION
**Pull request by pythonissam**

### CODE REVIEW

**Comment by wz1000** [comment]
I think this is a vscode-hie-server feature, not a haskell-ide-engine feature.

**Comment by alanz** [comment]
I think we need to note that this feature is (currently) unique to the vscode plugin, as it is implemented completely there.

**Comment by pythonissam** [comment]
@alanz @wz1000 So, is this accepted with noting that?

**Comment by alanz** [comment]
Yes, please add that note.

**Pull request merged**
