### PR TITLE
Use severity:3 (info) for hlint errors and warnings

### LINKED ISSUE #375: Use severity:3 (info) for hlint errors and warnings
Now it uses warnings (severity:2) so hints and warnings are blended together in neovim.

### PR DESCRIPTION
**Pull request by nponeccop**
Close #375

### CODE REVIEW

**Comment by alanz** [comment]
Looks good. And we lose a horribly typo.

Can you enable [circleci](https://circleci.com/) on your branch, so we can get a green before merging.

**Comment by nponeccop** [comment]
Haha I tried to change the setting of circleci but it didn't work. We can enable builds for all pull requests, even not from collaborators. But it seems it will work on newer requests from now on.

**Comment by alanz** [comment]
It builds against your repo, is my experience. I don't have enough authority to change the settings on the main github repo. Not sure who does, tbh.

But when you enable circleci, you can trigger it on the branch as a test, I am pretty sure.

**Comment by alanz** [comment]
And the first build takes around 6 hours.

We need to find a way to run GHC 8.0.2, 8.2.1 and 8.2.2. in parallel, on circle. 

It times out on travis

**Comment by nponeccop** [comment]
Ok a CircleCI build is queued now. 6 hours is too long, I remember stack projects with 240+ deps took less time to build on Travis. I'll investigate why Travis was so slow. And speaking of 8.0.2,  the current LTS snapshot works just fine (lts-9.14). Can I make a PR to change our old nightly snapshot?

**Comment by alanz** [comment]
Yes. I generally like to use the latest one that still supports the given compiler. But I'm so used to working with nightlies, did not even consider lts.

**Comment by nponeccop** [comment]
The situation with nightlies is a little confusing. Basically, nightlies are for unstable versions of compilers, and lts are for stable ones. (Stable ones are just those considered stable by snoyman/whoever maintains Stackage snapshots.) As 8.0.2 is stable, the latest build for it is lts-9.14 of 2017-11-18. Nightly builds for 8.0.2 stopped long ago, when it transitioned from unstable to stable.

**Comment by nponeccop** [comment]
Oh I didn't fix the tests so they still expect the old severities. And you were right - the 3 builds take about 6 hours :(

**Comment by alanz** [comment]
The first build takes the longest, after that it uses the cached  .stack stuff

**Pull request merged**
