### PR TITLE
Remove IdeResponse, split out IdeM into IdeM and IdeDeferM

### PR DESCRIPTION
**Pull request by Bubba**
- `codeActionProviders` can no longer defer
- Add `ifCachedModule`/`ifCachedModuleAndData` counterparts to `withCachedModule[AndData]`
- Remove `getCachedModule`/`isCached` to simplify/normalise how cached modules are accessed
- Remove `isStale` in `CachedModule` since it wasn't used

### CODE REVIEW

**Comment by Bubba** [comment]
@alanz @Infinisil do you still see the hang with this branch? I suspect it could be caused by HaRe's code actions, especially around here: https://github.com/haskell/haskell-ide-engine/blob/c6d95a258d20d33da01cbc52871f62d646cf061d/hie-plugin-api/Haskell/Ide/Engine/ArtifactMap.hs#L112-L137
Maybe it's getting stuck in a recursive loop?

**Comment by Bubba** [comment]
Should code actions also return instantly? In `LanguageClient-neovim` the request is triggered by the user rather than automatically when moving the cursor like in vscode, which would make sense for it to be a slow-running deferred request.

**Comment by alanz** [comment]
>  Should code actions also return instantly?

In vscode, and emacs-lsp, it is sent as part of the cursor movement, much like a hover request.

So speedy calculation is important.

**Comment by alanz** [comment]
This is behaving well for me so far, will likely merge tomorrow.

**Pull request merged**
