### PR TITLE
First pass at printing out debug info if started without --lsp

### LINKED ISSUE #1412: Implement a simple cli debugging command
It would be super useful to have an argument in `hie` which when passed causes hie to start, load the project, typecheck files, report any errors and exit. This would allow one to diagnose problems with hie's operation without setting up a lsp client.

Observe a run on `ghcide` with no arguments:

```
 $ ghcide
Starting ghcide (GHC v8.6)
/home/j/projects/upfind
[1/6] Finding hie-bios cradle
Cradle {cradleRootDir = "/home/j/projects/upfind", cradleOptsProg = CradleAction: default}

[2/6] Converting Cradle to GHC session

[3/6] Initialising IDE session

[4/6] Finding interesting files
Found 2 files

[5/6] Setting interesting files
[DEBUG] Set files of interest to: [NormalizedFilePath "./Setup.hs",NormalizedFilePath "./src/Main.hs"]
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)

[6/6] Loading interesting files
[DEBUG] Finishing shakeRun (took 0.00s, exception: thread killed)
[DEBUG] Starting shakeRun (aborting the previous one took 0.00s)
[DEBUG] Finishing shakeRun (took 0.15s, completed)
Files that worked: 2
Files that failed: 0
Done
```

The most important parts of this output to me are: 
- The root directory
- The files of interest 
- The number of working and failed files

It might be the case that this already exists, if so then it would be great to:

- Document this in the readme alongside searchable words like "debug" and "cli"
- Document this in `hie --help`

### PR DESCRIPTION
**Pull request by alanz**
Closes #1412 

Example output

```
Running HIE(hie)
  Version 1.0.0.0, Git revision 666626ede0e0bf5f1c876bd04f2a8a0cc68e7bb1 (dirty) (3534 commits) x86_64 ghc-8.6.5
Current directory:/home/alanz/mysrc/github/alanz/haskell-ide-engine/app

args:[]

Looking for project config cradle...

2020-01-01 22:41:46.396914848 [ThreadId 4] - Cabal-Helper dirs: ["/home/alanz/mysrc/github/alanz/haskell-ide-engine","/home/alanz/mysrc/github/alanz/haskell-ide-engine/app/File.hs"]
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following would be built (use -v for more details):
 - hie-plugin-api-0.14.0.0 (lib) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (lib) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (test:wrapper-test) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (exe:hie-wrapper) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (lib:hie-test-utils) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (exe:hie) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (test:unit-test) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (test:plugin-dispatcher-test) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (test:dispatcher-test) (configuration changed)
 - haskell-ide-engine-1.0.0.0 (test:func-test) (configuration changed)
Cradle:Cabal project
```

### CODE REVIEW

**Comment by alanz** [comment]
@bubba Perhaps, but until very recently (and not yet in a tagged release) we have always used the "--lsp" flag.

Also, this mimics what `ghcide` does, and I would rather maintain compatibility there.

**Comment by bubba** [comment]
@alanz We will need to update the README and vscode-hie-server for this, they currently do not contain the --lsp flag

**Comment by fendor** [comment]
Should we undo this then, or change the flags as @bubba suggested?

**Comment by alanz** [comment]
@fendor I updated the vscode client to include the --lsp flag again, I think we should let this stand, for now.

**Comment by fendor** [comment]
What about the other clients? Should update them somehow, too?

**Comment by alanz** [comment]
To my knowledge vscode and emacs-lsp are updated. Not sure what others need it, we should see reports if it is a problem. 

Luckily it is just a few days within a release, so they should be supporting the non-master stuff too. Maybe.

**Pull request merged**
