### PR TITLE
Hover response can now be null

### LINKED ISSUE #804: Returning malformed hover response when empty
At the moment we return a hover response of

```json
{"result":{"contents":[]},"jsonrpc":"2.0","id":2}
```
when we have no hover information.

This should be

```json
{"result":null,"jsonrpc":"2.0","id":2}
```
The empty contents is confusing the hover renderer in emacs-lsp.

See https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#hover-request-leftwards_arrow_with_hook

### PR DESCRIPTION
**Pull request by alanz**
Closes #804

### CODE REVIEW

**Comment by alanz** [comment]
The changes on haskell-lsp are not against master, as lsp-test still needs to be updated to use master.

**Comment by lorenzo** [comment]
Is this a fix for #804?

**Comment by alanz** [comment]
@lorenzo yes, thanks for the prompt

**Comment by Bubba** [comment]
Should we create a PR to haskell-lsp for these changes?

**Pull request merged**
