### PR TITLE
Test azure is working

### PR DESCRIPTION
**Pull request by Avi-D-coder**
Are azure runs consistent?

### CODE REVIEW

**Comment by jneira** [comment]
They don't. 🤷‍♂ 
`Timed out waiting to receive a message from the server.` from time to time (and others).
But i thought it is better to get some false negatives than to not have tests running.

**Comment by Avi-D-coder** [comment]
@jneira what are your thoughts on https://github.com/haskell/haskell-ide-engine/pull/1482#issuecomment-575980827?

**Comment by jneira** [comment]
@Avi-D-coder i've commented there

**Comment by Avi-D-coder** [comment]
Thanks for taking a look.

**Pull request closed without merging**
