### PR TITLE
Use LSP MarkupContent for generated documentation

### PR DESCRIPTION
**Pull request by alanz**
The affects the `HoverReply` message.

All documentation is now returned in markdown, and it renders much better in `emacs-lsp`.

### CODE REVIEW

**Comment by alanz** [comment]
The appveyor fail looks like a transient networking error, rather than an actual fail. And the linux equivalent passes. So I am going to merge (and hold thumbs).

**Comment by Infinisil** [comment]
I'm not sure if this or #1189 is the cause, but after the 0.9.0.0 update, [`lsp-ui-sideline`](https://github.com/emacs-lsp/lsp-ui#lsp-ui-sideline) started showing the raw markdown format:

**Comment by alanz** [comment]
I don't have that problem, and I am wondering if its because my emacs config explicitly pulls in `markdown-mode`.

```elisp
;; ---------------------------------------------------------------------
;; hie lsp stuff

(package-install 'dash-functional)
(package-install 'haskell-mode)
(package-install 'markdown-mode)
(require 'markdown-mode)
(package-install 'ht)
(package-install 'company-lsp)
(package-install 'yasnippet)
(require 'yasnippet)

;; (add-to-list 'load-path "/home/alanz/mysrc/github/alanz/lsp-mode")
(package-install 'lsp-mode)

;; (add-to-list 'load-path "/home/alanz/mysrc/github/alanz/lsp-ui")
(package-install 'lsp-ui)

;; (add-to-list 'load-path "/home/alanz/mysrc/github/alanz/lsp-haskell")
(package-install 'lsp-haskell)

;; New style client ;;;;;;;;;;;;;;
(require 'lsp)
(require 'lsp-haskell)
(add-hook 'haskell-mode-hook #'lsp)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ---- From
;;   https://github.com/tigersoldier/company-lsp -------
;;   http://company-mode.github.io/
;(package-install 'company-mode)
;(require 'company-mode)
(add-hook 'after-init-hook 'global-company-mode)

(require 'company-lsp)
(push 'company-lsp company-backends)
```

**Comment by alanz** [comment]
FYI, this is what I get

Screenshot from 2019-05-04 10-35-33

**Comment by Infinisil** [comment]
Doesn't seem to solve it, my config is [here](https://github.com/Infinisil/system/blob/1a1975e7a2b6f0eda6336e3fc5ee1c85ff536a48/config/emacs/modules/lsp.nix#L15) and [here](https://github.com/Infinisil/system/blob/1a1975e7a2b6f0eda6336e3fc5ee1c85ff536a48/config/emacs/modules/haskell.nix#L31) (there's an implicit `package-initialize` at the beginning to load all those packages).

I'll probably try to get a minimal example going to reproduce this (but not right now).

**Comment by Infinisil** [comment]
Ahh, so after updating `lsp-ui`, `lsp-mode` to latest master *and* installing `markdown-mode`, the problem is solved.

So `markdown-mode` should be a dependency of `lsp-haskell` probably

**Comment by Infinisil** [comment]
See also https://github.com/emacs-lsp/lsp-ui/issues/172

**Pull request merged**
