### PR TITLE
Ignore hlint errors instead of flushing all hlints 

### PR DESCRIPTION
**Pull request by Bubba**
Whenever ghc-mod returns an error it currently flushes all hlint diagnostics, even if hlint didn't necessarily have a parse error. This changes it to not flush the diagnostics and instead filters out the hlint errors in the first place. Should still keep #490

- [x] Add a config option

### CODE REVIEW

**Comment by Anrock** [comment]
@Bubba why closed?

**Comment by Bubba** [comment]
@Anrock after discussing with @alanz, this is actually the intended behaviour, https://github.com/haskell/haskell-ide-engine/issues/443
We could also look at making this an configurable setting?

**Comment by Anrock** [comment]
Hmm, this is confusing.

I see a reason in suppressing **errors** - there is no sense in having "parse error" from ghc and hlint at the same place, for example. 
However suppressing **hints** is a strange thing to do. 
Suppose, i'm writing a pattern match cases and despite parse error in current line (i didn't put a closing bracket yet) i still want to see a hint from hlint that pattern match is incomplete with unmatched pattern example. That's the real case and a reason i wanted this PR merged.

IMO, langserv should provide all info it has and client as a presentation layer should decide what to show or not.

**Comment by alanz** [comment]
@Anrock I agree, but I also think it may be useful for hie to have a configuration setting for this, to make it easier for client authors.

Especially as it is a pretty simple thing to do.

**Comment by Anrock** [comment]
@alanz i've checked lsp spec and it states that diagnostics are owned by server and client doesn't (even mustn't) do much with them, so this config option is actually pretty sane to be serverside. So i agree here.

**Comment by Bubba** [comment]
@alanz @Anrock is the consensus to add a config option for this then?

**Comment by Anrock** [comment]
@Bubba yep.

**Comment by Bubba** [comment]
@Anrock Then the real debate now is what should the default be 😛

**Comment by Anrock** [comment]
@Bubba while @alanz is away i vote for not flushing by default >_>

**Comment by alanz** [comment]
I would propose we keep the existing behaviour, unless the setting changes it.

This gives the least surprise to existing users.

**Pull request closed without merging**
