### PR TITLE
Use internal library for testing

### PR DESCRIPTION
**Pull request by bubba**
Now that stack 1.9.1 fixes bug https://github.com/commercialhaskell/stack/issues/4265

### CODE REVIEW

**Comment by lorenzo** [comment]
I guess you will need to bust the cache for the CI builders

**Comment by bubba** [comment]
I think we need to upgrade the stack version on the image too

**Comment by alanz** [comment]
And maybe we should wait a week or two to let more people update to stack 1.9.1 first

**Comment by bubba** [comment]
We’ll need to upgrade the circle CI docker image to use stack 1.9.1.
Should it be enough to just add a `RUN stack upgrade` to the Dockerfile?

**Comment by iGOTCHA34** [comment]
I need to get some info about how this works and what is the BEST way to do IT

**Comment by alanz** [comment]
LGTM, merge when the CI passes

**Pull request merged**
