### PR TITLE
Haskell lsp nightly

### PR DESCRIPTION
**Pull request by alanz**
Use `haskell-lsp-0.2.0.0` from the latest stackage nightly. For the GHC 8.2.1 build

### CODE REVIEW

**Comment by Tehnix** [comment]
Does this bring GHC 8.2 support for HIE, or is it still blocking on ghc-mod?

**Comment by alanz** [comment]
It is still blocked on ghc-mod /cabal-helper.

And I fear my next task is to dive into that swamp, as @DanielG does not seem to have the time to do it.

**Comment by Tehnix** [comment]
Ah, damn :( 

Perhaps there should be more coordination between GHC releases and core tooling such as this, although I understand that the cabal-helper update was quite big, with backpack and all.

**Comment by alanz** [comment]
Yes, backpack and new-build need to be digested. Both are *major* changes.

**Pull request merged**
