### PR TITLE
Mention hlint data file handling in readme

### LINKED ISSUE #872: failed to find requested hint files only on lts-12.*
```bash
2018-10-12 17:40:45.715944045 [ThreadId 4] - Current directory:/home/leshow/dev/haskell/haskell-programming-book/ProgrammingHaskell_Hutton
2018-10-12 17:40:45.742631268 [ThreadId 13] - Using stack GHC version
Using hie version: Version 0.2.2.0, Git revision 5d1d825880196eddbca4b1d12a60713f247c2a64 (1961 commits) x86_64 ghc-8.4.3
2018-10-12 17:40:45.882557696 [ThreadId 13] - requestDiagnostics: no diagFunc for:DiagnosticOnOpen
hie-8.4.3: user error (Failed to find requested hint files:
  /usr/bin/data/hlint.yaml
)
```

`/usr/bin/data` does not exist

This error only happens on 12.x LTS, 11.9 and others work fine.

I've installed from `haskell-ide-engine-git` in the AUR. Does anyone else have this issue? Any ideas?

### PR DESCRIPTION
**Pull request by jneira**
Closes #872

### CODE REVIEW

**Comment by Anrock** [comment]
As end-user: "Okay, hie must locate hlint file and will search at that path as a last resort. Where it will search in the first place?"

**Comment by jneira** [comment]
Uh, yeah, hlint has it own logic: afaik  cwd -> hlint_datadir(cabal/stack specific) env var -> $HOME -> executable current dir (the mentioned one)
Not sure about the order (but the last one) but it is hlint specific and i've dont fine a link in hlint docs to point to.
Do you think that should be reflected (i had to previously read the code/test)?

**Comment by Avi-D-coder** [comment]
I still have considerable doubts about this. It does not conform to standard UNIX packaging.
We can't place `hie` in `/usr/bin` since it would require making `/usr/bin/data/hlint.yaml`. 
The file-embed approach is far better.

**Comment by jneira** [comment]
Jumm i've checked where my installation is searching for the file:
* It looks in the dir pointed by $HLINT_DATADIR or the default one assigned by cabal/stack (inside cabal store or .stack_root)
* If that *directory* nos exists it looks for it in the `data` subdir in the dir where the executable is.
* At least using hlint as a library, it seems it doenst search in `cwd` or in `$HOME`.

@Avi-D-coder each option has it own caveats and we [decided ](https://github.com/haskell/haskell-ide-engine/issues/1143)finally to handle it like hlint itself, at least for now, without change any hie or hlint code. But i am open to talk about the file embed option, specially if it is done in hlint itself: maybe could we open an issue/pr in hlint to get feedback about?

or we can also reopen #1143 before that

**Comment by Avi-D-coder** [comment]
@jneira `$HLINT_DATADIR` is a runtime env right? A runtime env cannot be configured by most Linux package managers. Over riding at compile is also broken https://github.com/ndmitchell/hlint/issues/699

**Comment by jneira** [comment]
Oh, didnt know, i've just tested to set the en var  manually in my windows machine and it worked for me.
So i think it is worth to document how hie works right now but i will reopen the mentioned issue to discuss the file embed alternative.

**Comment by Avi-D-coder** [comment]
I sent in a file-embed PR https://github.com/ndmitchell/hlint/pull/824

**Comment by jneira** [comment]
@Anrock i've tested the different locations where the file is searched and i've added them

**Pull request merged**
