### PR TITLE
Prevent hie crash if hlint crashes

### PR DESCRIPTION
**Pull request by fendor**
Related to #1143 

Also improves stability of hie, thus related to #1146 
If hlint chokes on anything, dont kill hie.
An error message might be desirable but I dont know how to do that.

### CODE REVIEW

**Comment by mpickering** [comment]
There are already other functions which catch exceptions in HIE. Did you look at using one of those rather than rolling your own using `try`? In particular catching`SomeException` seems like quite a broad brush.

**Comment by fendor** [comment]
Indeed, catching `SomeException` is terrible.

**Comment by fendor** [comment]
Now we catch `IOExceptions`!

**Comment by power-fungus** [comment]
@mpickering I am actually in favor of aggressive error-catching from `hlint`. I think the `hie` language server should not be brought down by a internal error in any plugin like `hlint`. 

It is the best thing for `hie` to do is to stop the plugin `hlint` and possibly restart it since `hie` is still quite useful if one plugin is removed.

**Comment by mpickering** [comment]
@power-fungus The problem is catching async exceptions such as interrupts.

**Comment by power-fungus** [comment]
Indeed, async exceptions should not be caught

**Comment by bubba** [comment]
I would argue that language servers should be a bit overdramatic and crash frequently: VS Code automatically restarts the server if it dies, and from what I recall with the ghc-mod plugin, the design is to propagate as many fatal errors as possible

**Comment by fendor** [comment]
Hlint errors dont have to be fatal ones though. In that case, hlint would just not work, while other functionality is still working.

**Comment by Anrock** [comment]
I'm against being overdramatic, too. While VSCode may handle this well, LanguageClient-neovim stumbles on server crashes and i suspect other client may do this too. 

As a side note: LSP should be general overall, so coding against behaviour of specific client isn't right thing to do - remember embrace&extend&extuinguish. There are plenty of VSCode-specific quirks in other clients/servers already.

**Comment by Avi-D-coder** [comment]
The problem with crashing frequently is many language clients don't restart servers. If the server can recover it should try to. If possible plugins should be restarted. 
A message on stderr might also be a good idea.   Does anyone know how many clients handle stderr?

**Comment by alanz** [comment]
LGTM, now it is catching IOException.

**Pull request merged**
