### PR TITLE
Add EKG support

### PR DESCRIPTION
**Pull request by alanz**
Launch with the `--ekg` option to `hie`, and point a browser at
http://localhost:8000

### CODE REVIEW

**Comment by soylens** [comment]
Is this the TCP/IP interface the Atom client(win) mentions?

**Comment by alanz** [comment]
No, this is a mini web server giving a view into the running HIW process, to see memory, cpu etc usage.

See https://hackage.haskell.org/package/ekg

**Comment by soylens** [comment]
There should probably be a command line option to specify the port in case localhost:8000 is occupied

**Comment by alanz** [comment]
I agree.

**Pull request merged**
