### PR TITLE
Make completions fuzzy, utilize cachedData and prevent it from being overwritten

### PR DESCRIPTION
**Pull request by dpren**

### CODE REVIEW

**Comment by alanz** [comment]
I am happy to merge this, then we can try to understand current issues and work from there.

The module caching in master is already broken, this does make it somewhat better.

I am still seeing issues on hover though, which seems not to be async anymore.. Or is async, but does not use the stored module.

**Comment by wz1000** [comment]
See https://github.com/dpren/haskell-ide-engine/pull/1

**Comment by wz1000** [comment]
Another thing - I don't seem to get completion results for qualified items imported without explicit qualification

For example

    import Data.Map
    Map.

will not give me completions for all the stuff inside Map. It would be nice if it could handle this case.

**Comment by dpren** [comment]
Ok, I think I'm covering all the import cases now.
https://wiki.haskell.org/Import

**Pull request merged**
