### PR TITLE
Ghcmod commands

### PR DESCRIPTION
**Pull request by alanz**
Adding some more ghc-mod commands

### CODE REVIEW

**Comment by alanz** [comment]
@gracjan, @JPMoresmau, @cocreature 

Please review this and merge if happy

**Comment by gracjan** [comment]
@alanz: Can you rebase it in a way so that commit 400fac7 goes completely away? `git rebase origin/master` should do the trick.

**Comment by gracjan** [comment]
Same with commits 3990a62 and f3f3c93.

**Comment by gracjan** [comment]
I think you should just squash it as one single commit. There is still some unnecessary history left in here.

**Comment by gracjan** [comment]
Otherwise it looks great.

**Pull request merged**
