### PR TITLE
Document Atom integration

### PR DESCRIPTION
**Pull request by domenkozar**
Haven't tested it yet, as I need to upgrade Atom first.

cc @lierdakil

### CODE REVIEW

**Comment by lierdakil** [comment]
That thing's not *really* supported -- that's why it wasn't published on atom.io. So I'd prefer to avoid endorsing it, tbh. It's fine for what it is though -- a quick-and-dirty way to get hie working in Atom.

**Comment by Tehnix** [comment]
I think there are some low hanging fruits for getting HIE somewhat functional on Atom. I've explored a bit with the just released updates to the LSP server [here](https://github.com/Tehnix/atom-haskell-hie) if anyone is interested, running on Atom beta 1.21. 

_Code actions_ for example seem like minor work, if you have experience with Atom plugins, and I'm sure there is some obvious bug with the _code format_.

**Comment by domenkozar** [comment]
Thanks @Tehnix :) I'll get the beta Atom and give this a go soon!

**Comment by domenkozar** [comment]
@Tehnix I have installed it with atom-ide and atom-language-server, but I still see no GUI. Is there something I should enable first?

**Comment by Tehnix** [comment]
@domenkozar It should work after installing `apm install atom-ide-ui atom-haskell-hie` and then you also need the HIE executable itself available on your path.

**Comment by domenkozar** [comment]
Atom 1.21.0 has been released 3 days ago \o/ I'll give this a go soon.

**Comment by JonCoens** [comment]
Piggybacking, has anyone looked at integrating with Nuclide and not just Atom?

**Comment by Tehnix** [comment]
@JonCoens I thought atom-ide-ui was part of Nuclide (https://nuclide.io/blog/2017/09/12/Introducing-Atom-IDE-UI/)? Or are you more referring to https://github.com/facebook/nuclide/tree/master/pkg/nuclide-language-service? 

I would be up for taking a look :)

**Comment by Tehnix** [comment]
Also, I just want to add that HIE with `apm install nuclide atom-haskell-hie` (or just `apm install atom-ide-ui atom-haskell-hie`) is working quite nicely atm :)

**Comment by JonCoens** [comment]
Yes, apologies for not be specific. I'm keen to bring HIE to facebook's Nuclide.

**Comment by Tehnix** [comment]
Just a note that `atom-haskell-hie` have been renamed to [`ide-haskell-hie`](https://github.com/Tehnix/ide-haskell-hie). I realize this might cause a bit of confusion with the existing `ide-haskell`, but it's to follow the convention set up by https://github.com/atom/atom-languageclient which allows for better discoverability (e.g. if the outline view is open in a haskell file with no LSP yet, it'll link you to an automatic search for `ide-<language>`).

Also, [`ide-haskell-hie`](https://github.com/Tehnix/ide-haskell-hie) seems to be working quite well with HIE, and in fact I'm currently using it as my only package for Haskell editing on Atom. Code actions and code format also work now.

Would appreciate more testers of course, but it might be ready to add to the readme? Le me know, and I'll submit a PR for it.

**Comment by Tehnix** [comment]
I'll close this as it ended up being included as part of #348, and the Nuclide conversation was moved to #344.

**Pull request closed without merging**
