### PR TITLE
Add 8.8.2 stack file and CI

### PR DESCRIPTION
**Pull request by bubba**

### CODE REVIEW

**Comment by Avi-D-coder** [comment]
@jneira is 8.8.2 working on windows?

**Comment by bubba** [comment]
> Actually, is Azure CI missing?

I'm not familiar with the Azure stuff, can you or @jneira handle this afterwards?

**Comment by jneira** [comment]
@Avi-D-coder last time i tried with cabal i hit a compilation error involving haddkock-api but i'll try again

**Comment by jneira** [comment]
Lot of test errors with ghc-8.2.2, are they present in local tests?

**Comment by jneira** [comment]
The compile error with cabal is 
```
[14 of 40] Compiling Haddock.Convert  ( src\Haddock\Convert.hs, dist\build\Haddock\Convert.o )

src\Haddock\Convert.hs:621:39: error:
    • Variable not in scope: injectiveVarsOfBinder :: TyConBinder -> FV
    • Perhaps you meant ‘injectiveVarsOfType’ (imported from TyCoRep)
    |
621 |                            mapUnionFV injectiveVarsOfBinder dropped_binders
    |                                       ^^^^^^^^^^^^^^^^^^^^^
cabal.exe: Failed to build haddock-api-2.23.0 (which is required by
test:wrapper-test from haskell-ide-engine-1.0.0.0, test:unit-test from
haskell-ide-engine-1.0.0.0 and others)
```

**Comment by jneira** [comment]
Trying with cabal after adding
```
source-repository-package
    type: git
    location: https://github.com/haskell/haddock.git
    subdir: haddock-api
    tag: be8b02c4e3cffe7d45b3dad0a0f071d35a274d65
```
in `cabal.project`

**Comment by jneira** [comment]
I am getting this compile error in windows using stack:
```
ormolu               > D:\sr\snapshots\f5723ebd\lib\x86_64-windows-ghc-8.8.2\ghc-lib-parser-8.8.2-75ZOMeqOpqa23xhx9rJVRy\HSghc-lib-parser-8.8.2-75ZOMeqOpqa23xhx9rJVRy.o: unhandled PEi386 relocation type 0
ormolu               > ghc.exe: unable to load package `ghc-lib-parser-8.8.2'
```

I've added ghc-8.8.2 to azure anyway

**Comment by jneira** [comment]
The fix for windows to be able to build Cabal [was not included in ghc-8.8.2](https://gitlab.haskell.org/ghc/ghc/merge_requests/2473#note_246982), it has been [backported to 8.8.3](https://gitlab.haskell.org/ghc/ghc/merge_requests/2349) :sob: 

I am getting the same error for windows building it with cabal than ghc-8.8.1:
```
ghc.exe: unable to load package `Cabal-3.0.1.0'
ghc.exe:  | D:\Trabajo\NO-SALVAR\jneira\bin\Programs\stack\x86_64-windows\ghc-8.8.2\lib\Cabal-3.0.1.0\HSCabal-3.0.1.0.o: unknown symbol `.file'
cabal.exe: Failed to build lib:c-h-internal from cabal-helper-1.0.0.0 (which
is required by test:wrapper-test from haskell-ide-engine-1.0.0.0,
test:unit-test from haskell-ide-engine-1.0.0.0 and others). See the build log
above for details.
```
So i have to remove this version from windows too :disappointed:

**Comment by bubba** [comment]
The linux CircleCI tests were failing because I forgot to update the testutils with the new version, committing that fix now

> The fix for windows to be able to build Cabal [was not included in ghc-8.8.2](https://gitlab.haskell.org/ghc/ghc/merge_requests/2473#note_246982), it has been [backported to 8.8.3](https://gitlab.haskell.org/ghc/ghc/merge_requests/2349) 😭

Argh, c'est la vie.

**Pull request merged**
