### PR TITLE
Bump stack resolvers

### PR DESCRIPTION
**Pull request by bubba**
Bring both the nightly and 8.4.4 stack files to lts12.17. Eventually the nightly will point to the 8.6.1 nightlies?

### CODE REVIEW

**Comment by lorenzo** [comment]
@bubba Have you tried to compile with 8.6 already?

**Comment by bubba** [comment]
@Lorenzo It fails due to cabal-helper et al., last time I checked we're waiting on it to get updated #844

**Comment by alanz** [comment]
@bubba I think circle messed this one up, perhaps restart the builds

**Comment by bubba** [comment]
@alanz Looks like something its still failing, will try testing it locally

**Pull request merged**
