### PR TITLE
cabal new-build merged from arbor repo

### PR DESCRIPTION
**Pull request by alanz**
This is a merge of #905, bringing in the work they have done on `cabal-helper` and `ghc-mod` to support `cabal new-build` in addition to the existing `cabal build` and stack support.

I will be running it for a few days to get a feel for it, before merging.

And I think prior to the merge we should bump a version and tag it, so people have a clear point to return to if we hit problems with this.

Thanks to @dsturnbull for creating the original patch.

### CODE REVIEW

**Comment by alanz** [comment]
@dsturnbull I see that the identification of a preinstalled `Cabal` library has changed,

```
-listCabalVersions :: Options -> IO [Version]
+listCabalVersions :: Options -> MaybeT IO [Version]
 listCabalVersions opts = listCabalVersions' opts Nothing
 
--- TODO: Include sandbox? Probably only relevant for build-type:custom projects.
-listCabalVersions' :: Options -> Maybe PackageDbDir -> IO [Version]
-listCabalVersions' Options {..} mdb = do
-  let mdbopt = ("--package-conf="++) <$> unPackageDbDir <$> mdb
-      opts = ["list", "--simple-output", "Cabal"] ++ maybeToList mdbopt
-
-  catMaybes . map (fmap snd . parsePkgId . fromString) . words
-          <$> readProcess oGhcPkgProgram opts ""
+listCabalVersions' :: Options -> Maybe PackageDbDir -> MaybeT IO [Version]
+listCabalVersions' opts@Options {..} mdb = do
+  case mdb of
+    Nothing -> mzero
+    Just (PackageDbDir db_path) -> do
+      exists <- liftIO $ doesDirectoryExist db_path
+      case exists of
+        False -> mzero
+        True  -> MaybeT $ logIOError opts "listCabalVersions'" $ Just <$> do
+          let mdbopt = ("--package-conf="++) <$> unPackageDbDir <$> mdb
+              args = ["list", "--simple-output", "Cabal"] ++ maybeToList mdbopt
+
+          catMaybes . map (fmap snd . parsePkgId . fromString) . words
+                   <$> readProcess' opts oGhcPkgProgram args ""
```
the critical feature being that if `Nothing` is passed in as the possible package db location it does not even try to look for anything. And it is pretty much always used with `Nothing`, via the `listCabalVersions` call.

Is this deliberate? Is it because of the `.ghc.env*` files?

This results in the `Cabal` library being recompiled pretty much every time the wrapper is rebuilt, which is a huge delay and waste.

**Comment by alanz** [comment]
I think this is ready to land.

I have tested it locally on a cabal old build, cabal new one, and a stack one, and it seems to behave.

Any reasons not to merge once CI is complete?

cc @dsturnbull

**Comment by newhoggy** [comment]
I'm @dsturnbull's colleague.  @dsturnbull might be disappearing for a few days.

@AlexeyRaga and I have looked at the snippet you posted and it looks like it wasn't due to any of our commits.

Ping @DanielG 

```
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 663) listCabalVersions :: Options -> MaybeT IO [Version]
c7aba0db CabalHelper/Compile.hs                 (Daniel Gröber 2015-08-21 06:34:09 +0200 664) listCabalVersions opts = listCabalVersions' opts Nothing
c7aba0db CabalHelper/Compile.hs                 (Daniel Gröber 2015-08-21 06:34:09 +0200 665)
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 666) listCabalVersions' :: Options -> Maybe PackageDbDir -> MaybeT IO [Version]
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 667) listCabalVersions' opts@Options {..} mdb = do
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 668)   case mdb of
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 669)     Nothing -> mzero
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 670)     Just (PackageDbDir db_path) -> do
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 671)       exists <- liftIO $ doesDirectoryExist db_path
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 672)       case exists of
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 673)         False -> mzero
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 674)         True  -> MaybeT $ logIOError opts "listCabalVersions'" $ Just <$> do
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 675)           let mdbopt = ("--package-conf="++) <$> unPackageDbDir <$> mdb
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 676)               args = ["list", "--simple-output", "Cabal"] ++ maybeToList mdbopt
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 677)
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 678)           catMaybes . map (fmap snd . parsePkgId . fromString) . words
9142d8a9 src/CabalHelper/Compiletime/Compile.hs (Daniel Gröber 2018-08-12 04:45:34 +0200 679)                    <$> readProcess' opts oGhcPkgProgram args ""
```

**Comment by alanz** [comment]
@newhoggy thanks for the info. Based on behaviour I think reverting it was the right thing to do though.

**Pull request merged**
