### PR TITLE
Allow newer optparse-applicative for ormolu (stack version)

### PR DESCRIPTION
**Pull request by jneira**
* Follow up of #1583
* Temporary workaround until #1579 (or upstream fix) is merged

### CODE REVIEW

**Comment by alanz** [comment]
Is it only a big switch in stack? No finer grain possibility?

**Comment by Avi-D-coder** [comment]
@alanz As far as I know there is no fine grain support.

**Comment by jneira** [comment]
Linux job for stack-8.8.1.yaml is failing with:
```
haskell-ide-engine> /home/vsts/work/1/s/src/Haskell/Ide/Engine/Plugin/Ormolu.hs:15:1: error: [-Wunused-imports, -Werror=unused-imports]
haskell-ide-engine>     The import of ‘Ormolu.Config’ is redundant
haskell-ide-engine>       except perhaps to import instances from ‘Ormolu.Config’
haskell-ide-engine>     To import instances alone, use: import Ormolu.Config()
haskell-ide-engine>    |
haskell-ide-engine> 15 | import Ormolu.Config (defaultConfig)
haskell-ide-engine>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
haskell-ide-engine> 
haskell-ide-engine> /home/vsts/work/1/s/src/Haskell/Ide/Engine/Plugin/Ormolu.hs:16:1: error: [-Wunused-imports, -Werror=unused-imports]
haskell-ide-engine>     The import of ‘Ormolu.Exception’ is redundant
haskell-ide-engine>       except perhaps to import instances from ‘Ormolu.Exception’
haskell-ide-engine>     To import instances alone, use: import Ormolu.Exception()
haskell-ide-engine>    |
haskell-ide-engine> 16 | import Ormolu.Exception (OrmoluException)
haskell-ide-engine>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Completed 2 action(s).
```

It seems there is no job in circleci for stack-8.8.1 yet.

**Comment by jneira** [comment]
well this is needed to even build it, so merge

**Pull request merged**
