### PR TITLE
Add installation instructions for windows users

### PR DESCRIPTION
**Pull request by ShrykeWindgrace**
Add installation instructions for windows users who are facing the `path too long` issue on windows. Addresses #435

### CODE REVIEW

**Comment by alanz** [comment]
Thanks. Every bit helps

**Comment by nponeccop** [comment]
@alanz apparently it's not #435 but an unrelated issue. And now we have an instruction suggesting fairly terrible things to everyone on Windows. While in fact it's not for everyone but for those using " haskell-ide-engine somewhere deep in folder hierarchy" as @ShrykeWindgrace put it in #435.

The practice of creating anything out of home folder is as terrible on Windows as it is on Linux (although historically nobody cares - the tradition does back all the way to DOS and it's predecessors). "Normal" folders complying with Windows analog of Filesystem Hierarchy Standard such as `c:\users\username\Documents\dev\foo\bar\quux\haskell-ide-engine` work just fine, the path just cannot be too long. So the suggestion should explicitly mean that it's a workaround for a rarely encountered issue.

**Comment by alanz** [comment]
Ok, so what to do?

**Comment by nponeccop** [comment]
> the installation instruction should explicitly mention that it's a workaround for a rarely encountered issue.

Either I or @ShrykeWindgrace will change the instruction text when we have time. Hopefully tomorrow.

**Comment by ShrykeWindgrace** [comment]
On a second thought, I'd say it's better to revert the merge altogether. The workaround is windows-centric and has little to do with `hie` itself.

**Pull request merged**
