### PR TITLE
WIP: Remove Makefile & build-all.ps1

### LINKED ISSUE #1033: Remove Makefile & build-all.ps1 and leave only Shakefile
Hey, three build scripts are too much.

Right now I'm making a PR that removes both Makefile and build-all.ps1 and updates README about that (also some DRY cleanups).

Is there any objections or specific blockers to using Shake script as the only build script?

Todo:
- [x] Add 8.4.2 and 8.2.1 versions to `hieVersions` list in Shakefile #1034
- [x] Remove v1 prefix from cabal commands (#1043)
- [x] Rename Shakefile to install.hs and update README (#1044)
- [x] Remove mentions of Make/build-all.ps1 from README (~~#1120~~)
- [x] Actually remove Makefile and build-all.ps1 scripts. (#1140)
- [x] Make sure that Shakefile implements everything as Makefile does (~~#1032~~, ???) 
- [ ] Add some CI tests (separate PR by @bubba)

### PR DESCRIPTION
**Pull request by Anrock**
Closes #1033 

TODO:
- [ ] Make sure that Shakefile implements everything as Makefile does (~~#1032~~, ???) 
- [ ] Rename Shakefile to install.hs and update README
- [ ] Remove v1 prefix from cabal commands (~~#1043~~)
- [ ] Actually remove Makefile and build-all.ps1 scripts.
- [ ] Add some CI tests (separate PR by @bubba)

### CODE REVIEW

**Comment by alanz** [comment]
I think we should include something in CI that builds using this, preferably on all the platforms we support.

**Comment by Anrock** [comment]
I've compared shakefile and makefile and the only notable difference i've found is cabal target. Otherwise they look almost identical.
Makefile:
```make
cabal:
	stack install cabal-install
	cabal update
	cabal install Cabal-2.4.1.0 --with-compiler=$(GHC)
```
Shakefile:
```haskell
installCabal :: GhcPath -> Action ()
installCabal ghc = do
  execStack_ ["install", "cabal-install"]
  execCabal_ ["v1-update"]
  execCabal_ ["v1-install", "Cabal-2.4.1.0", "--with-compiler=" ++ ghc]
```
And i have no idea what's the difference between, for example, `cabal install` and `cabal v1-install`. I assume that `cabal install` is implicitly calls `v1-install` until `v2` commands are default, right? Can someone comment on this?

@bubba can you take CI tests part? I have no experience in that.

**Comment by bubba** [comment]
@Anrock Yep! I'll add some basic tests on CircleCI

**Comment by alanz** [comment]
@Anrock we took out the v1-prefix on the cabal stuff because some cabal versions for the earlier GHC compilers don't understand them.

**Comment by Anrock** [comment]
@bubba thanks!
@alanz so i should remove them from Shakefile as well, right? Regarding renaming - i'll rename it to install.hs then.

**Comment by alanz** [comment]
@Anrock yes, I think remove the `v1-` prefixes, and `install.hs` sounds fine.

**Comment by bubba** [comment]
Sorry - this is from me trying to add a test on this branch. Feel free to revert the commit and merge, I can open a separate PR for it later today

**Comment by Anrock** [comment]
I would rather wait for PR with Shake tests before proceeding with this one.

CI error indicates that it's probably an out of memory error. Can somenone just try restarting it and see if it still fails?

**Comment by bubba** [comment]
@Anrock the workspace-sharing setup between jobs isn't working in the shakefile job, causing it to try and rebuild the entire thing from scratch, its most caused by me butchering something in the config.yml file

**Comment by Anrock** [comment]
@bubba ok. I'll rebase this PR on master throwing out your commits then.

**Comment by Anrock** [comment]
I find it easier to implement this via multiple self-contained PRs, so i'm closing this. Todo list copied to #1033.

**Pull request closed without merging**
