### PR TITLE
Error structure with code

### PR DESCRIPTION
**Pull request by JPMoresmau**
Hello, not sure if that's useful, but at least it forced me to have a look a bit everywhere in the code (-:. This replaces simple string errors by more structured ones, with a code, a human readable string and some JSON parameters. Also, I've removed calls to error to return IdeResponseFail.

### CODE REVIEW

**Comment by alanz** [comment]
It looks good, just have some simple travis failures

**Comment by JPMoresmau** [comment]
Oh, how come Travis builds with -Werror? I could of course build properly on my machine with stack build. Will fix later. thanks!

**Comment by alanz** [comment]
ok, I added a makefile and test locally with

    make test

This builds with -Werror and runs the elisp tests too, so is representative
of the travis environment

**Comment by JPMoresmau** [comment]
Warnings and tests addressed, make test is now successful.

**Comment by alanz** [comment]
Except you missed by a few minutes, need to merge now

**Comment by JPMoresmau** [comment]
Yep!! I'll do the merge on my side. Pray for me...

**Comment by alanz** [comment]
Should be pretty straightforward, I hope. I'm doing it too for my PR

**Pull request merged**
