### PR TITLE
Remove some old cruft from README

### PR DESCRIPTION
**Pull request by DanielG**
See individual commits for justification for throwing these paragraphs away.

The basic idea of a README should be to welcome new users and point them in the right direction. Droning on about old projects isn't really helping that goal.

### CODE REVIEW

**Comment by Anrock** [comment]
Personally i'm all in for README as welcoming and quick start document. Everything else should go to docs.

**Comment by alanz** [comment]
LGTM.

A part of me wonders if/when we should move toward a readthedocs type approach to this.

**Comment by bubba** [comment]
@alanz is it time to reconsider the github wiki?

**Comment by alanz** [comment]
Well, people are more likely to propose changes to a doc via a PR, tend not to want to edit a Wiki, because there is no approval stage.

So docs in the repo as we have now is good, with a PR flow.

So I guess we just need to consider how we organise the docs we have, so that it is useful.

And as a later/different concern decide whether we need to separately publish the docs. It is probably too early for that.

**Pull request merged**
